### ISSUE TITLE
Add editing video time < 60s

### ISSUE THREAD

**Issue by alexdo83** [fabrree/videoGenerator#6]
Add editing video time < 60s : Is it possible to edit the timing of the video? I think it's better to customize it

**Comment by fabrree** [comment]
Can you please specify what you mean? You want the video to consist of multiple clips instead of one?

**Comment by DuxSec** [comment]
@anhdodotnet Can you please specify what you mean? You want the video to consist of multiple clips instead of one?

**Comment by alexdo83** [comment]
> @anhdodotnet Can you please specify what you mean? You want the video to consist of multiple clips instead of one?

1. Is it possible to manually adjust the video length?
2. background video could be more?
3. Quote scraping from API (eg: https://github.com/elebumm/RedditVideoMakerBot)
4.  ....

**Comment by DuxSec** [comment]
> > @anhdodotnet Can you please specify what you mean? You want the video to consist of multiple clips instead of one?
> 
> 1. Is it possible to manually adjust the video length?
> 2. background video could be more?
> 3. Quote scraping from API (eg: https://github.com/elebumm/RedditVideoMakerBot)
> 4. ....

1. This is currently difficult to do because of the time the video plays, this would mean the video has to be looped (or a video with enough time needs to be scraped from the api, I need to check if they have those, this might take quite some time downloading though).

2. Refer to 1.

3. 2 day's ago someone else added a PR, this will be updated.

**Comment by DuxSec** [comment]
fixed
